script: |
            # Confirm a successful SSH connection
            echo "SSH connection established."
            
            # Check if the directory exists and the user has access
            if [ -d "/var/www/app" ]; then
              echo "Directory /var/www/app exists."
              cd /var/www/app
              echo "Successfully navigated to application directory."
            else
              echo "ERROR: Directory /var/www/app does not exist or is inaccessible."
              exit 1
            fi
            
            # Placeholder for your next commands
            echo "Script finished. Add your next commands here."